export const ROUTE_NAMES = {
  Splash: 'Splash',
  AuthGroup: 'AuthGroup',
  Welcome: 'Welcome',
  Login: 'Login',
  SessionRecovery: 'SessionRecovery',
  AccessDenied: 'AccessDenied',
  OnboardingName: 'OnboardingName',
  OnboardingDateOfBirth: 'OnboardingDateOfBirth',
  OnboardingGender: 'OnboardingGender',
  OnboardingPhotoUpload: 'OnboardingPhotoUpload',
  OnboardingBio: 'OnboardingBio',
  OnboardingPreferences: 'OnboardingPreferences',
  OnboardingTerms: 'OnboardingTerms',
  ProfileCompletionRequired: 'ProfileCompletionRequired',
  NearbyVenues: 'NearbyVenues',
  VenueDetails: 'VenueDetails',
  DiscoveryProfilePreview: 'DiscoveryProfilePreview',
  CheckInConfirmation: 'CheckInConfirmation',
  CheckoutConfirmation: 'CheckoutConfirmation',
  UserProfile: 'UserProfile',
  EditProfile: 'EditProfile',
  ProfilePhotosManagement: 'ProfilePhotosManagement',
  AccountSettings: 'AccountSettings',
  LinkedAccounts: 'LinkedAccounts',
  DeleteAccount: 'DeleteAccount',
  AccountDeletionRecovery: 'AccountDeletionRecovery',
  UserGroup: 'UserGroup',
  OwnerGroup: 'OwnerGroup',
  ModeratorGroup: 'ModeratorGroup',
  AdminGroup: 'AdminGroup',
  UnknownRouteFallback: 'UnknownRouteFallback',
} as const;

export type AppRouteName = (typeof ROUTE_NAMES)[keyof typeof ROUTE_NAMES];

export const ROUTE_MODULE_OWNERS = {
  AppShell: 'app-shell',
  Auth: 'auth',
  User: 'user',
  VenueOwner: 'venue-owner',
  Moderation: 'moderation',
  Administration: 'administration',
} as const;

export type RouteModuleOwner = (typeof ROUTE_MODULE_OWNERS)[keyof typeof ROUTE_MODULE_OWNERS];

export const ROUTE_GROUP_OWNERSHIP: Record<AppRouteName, RouteModuleOwner> = {
  [ROUTE_NAMES.Splash]: ROUTE_MODULE_OWNERS.AppShell,
  [ROUTE_NAMES.AuthGroup]: ROUTE_MODULE_OWNERS.Auth,
  [ROUTE_NAMES.Welcome]: ROUTE_MODULE_OWNERS.Auth,
  [ROUTE_NAMES.Login]: ROUTE_MODULE_OWNERS.Auth,
  [ROUTE_NAMES.SessionRecovery]: ROUTE_MODULE_OWNERS.Auth,
  [ROUTE_NAMES.AccessDenied]: ROUTE_MODULE_OWNERS.Auth,
  [ROUTE_NAMES.OnboardingName]: ROUTE_MODULE_OWNERS.Auth,
  [ROUTE_NAMES.OnboardingDateOfBirth]: ROUTE_MODULE_OWNERS.Auth,
  [ROUTE_NAMES.OnboardingGender]: ROUTE_MODULE_OWNERS.Auth,
  [ROUTE_NAMES.OnboardingPhotoUpload]: ROUTE_MODULE_OWNERS.Auth,
  [ROUTE_NAMES.OnboardingBio]: ROUTE_MODULE_OWNERS.Auth,
  [ROUTE_NAMES.OnboardingPreferences]: ROUTE_MODULE_OWNERS.Auth,
  [ROUTE_NAMES.OnboardingTerms]: ROUTE_MODULE_OWNERS.Auth,
  [ROUTE_NAMES.ProfileCompletionRequired]: ROUTE_MODULE_OWNERS.Auth,
  [ROUTE_NAMES.NearbyVenues]: ROUTE_MODULE_OWNERS.User,
  [ROUTE_NAMES.VenueDetails]: ROUTE_MODULE_OWNERS.User,
  [ROUTE_NAMES.DiscoveryProfilePreview]: ROUTE_MODULE_OWNERS.User,
  [ROUTE_NAMES.CheckInConfirmation]: ROUTE_MODULE_OWNERS.User,
  [ROUTE_NAMES.CheckoutConfirmation]: ROUTE_MODULE_OWNERS.User,
  [ROUTE_NAMES.UserProfile]: ROUTE_MODULE_OWNERS.User,
  [ROUTE_NAMES.EditProfile]: ROUTE_MODULE_OWNERS.User,
  [ROUTE_NAMES.ProfilePhotosManagement]: ROUTE_MODULE_OWNERS.User,
  [ROUTE_NAMES.AccountSettings]: ROUTE_MODULE_OWNERS.User,
  [ROUTE_NAMES.LinkedAccounts]: ROUTE_MODULE_OWNERS.User,
  [ROUTE_NAMES.DeleteAccount]: ROUTE_MODULE_OWNERS.User,
  [ROUTE_NAMES.AccountDeletionRecovery]: ROUTE_MODULE_OWNERS.User,
  [ROUTE_NAMES.UserGroup]: ROUTE_MODULE_OWNERS.User,
  [ROUTE_NAMES.OwnerGroup]: ROUTE_MODULE_OWNERS.VenueOwner,
  [ROUTE_NAMES.ModeratorGroup]: ROUTE_MODULE_OWNERS.Moderation,
  [ROUTE_NAMES.AdminGroup]: ROUTE_MODULE_OWNERS.Administration,
  [ROUTE_NAMES.UnknownRouteFallback]: ROUTE_MODULE_OWNERS.AppShell,
};